#Faça um programa que leia um número inteiro qualquier e mostre na tela a sua tabuada.
n = int(input('Qual número deseja realizar a tabuada? '))
x0 = (n*0)
x1 = (n*1)
x2 = (n*2)
x3 = (n*3)
x4 = (n*4)
x5 = (n*5)
x6 = (n*6)
x7 = (n*7)
x8 = (n*8)
x9 = (n*9)
print('-'*15)
print(f'; {n}x0={x0} \n; {n}x1={x1} \n; {n}x2={x2} \n; {n}x3={x3} \n; {n}x4={x4} \n; {n}x5={x5} \n; {n}x6={x6} \n; {n}x7={x7} \n; {n}x8={x8} \n; {n}x9={x9}')
print('-'*15)